# =============================================================================
# CoTrain Monorepo Workspace Configuration
# =============================================================================
# This file defines the workspace structure for the CoTrain project
# using pnpm workspaces for efficient dependency management

# Workspace packages configuration
# Only includes directories that actually exist in the project
packages:
  # Applications - only existing apps
  - 'apps/*'
  
  # Shared packages - only existing packages
  - 'packages/*'
  
  # Note: CotrainCore is a Python project with its own dependency management
  # Note: move/ directory contains Aptos smart contracts (Move language)
  # Note: configs/ directory contains shared configuration files, not packages

# Catalog configuration for shared dependencies
# Updated to match actual versions used in the project
catalog:
  # React ecosystem
  react: ^18.3.1
  react-dom: ^18.3.1
  
  # Next.js
  next: ^15.2.4
  
  # TypeScript
  typescript: ^5.4.5
  '@types/node': ^20.0.0
  '@types/react': ^18.3.3
  '@types/react-dom': ^18.3.0
  
  # NestJS
  '@nestjs/core': ^10.0.0
  '@nestjs/common': ^10.0.0
  '@nestjs/platform-express': ^10.0.0
  '@nestjs/config': ^3.1.1
  '@nestjs/typeorm': ^10.0.1
  '@nestjs/jwt': ^10.2.0
  '@nestjs/passport': ^10.0.2
  '@nestjs/swagger': ^7.1.17
  
  # Database
  typeorm: ^0.3.17
  pg: ^8.11.3
  redis: ^4.6.10
  
  # Aptos SDK
  '@aptos-labs/ts-sdk': ^1.39.0
  '@aptos-labs/wallet-adapter-react': ^6.1.2
  '@aptos-labs/wallet-adapter-core': ^5.7.1
  
  # UI Libraries
  '@radix-ui/react-dialog': ^1.0.5
  '@radix-ui/react-dropdown-menu': ^2.0.6
  '@radix-ui/react-slot': ^1.0.2
  '@radix-ui/react-toast': ^1.1.5
  '@radix-ui/react-tooltip': ^1.1.6
  
  # Styling
  tailwindcss: ^3.4.1
  clsx: ^2.1.1
  class-variance-authority: ^0.7.0
  tailwind-merge: ^2.5.5
  
  # State Management
  zustand: ^5.0.6
  '@tanstack/react-query': ^5.83.0
  
  # Forms and Validation
  'react-hook-form': ^7.54.1
  '@hookform/resolvers': ^3.9.1
  zod: ^3.24.1
  
  # Testing
  jest: ^29.5.0
  
  # Linting and Formatting
  eslint: ^8.42.0
  prettier: ^3.3.1
  '@typescript-eslint/eslint-plugin': ^6.0.0
  '@typescript-eslint/parser': ^6.0.0
  
  # Utilities
  lodash: ^4.17.21
  date-fns: ^4.1.0
  uuid: ^9.0.1
  bcryptjs: ^2.4.3

# Package manager settings
packageManager: pnpm@8.15.0

# Auto install peers
auto-install-peers: true

# Strict peer dependencies
strict-peer-dependencies: false

# Engine strict
engine-strict: true

# Link workspace packages
link-workspace-packages: true

# Prefer workspace packages
prefer-workspace-packages: true

# Save workspace protocol
save-workspace-protocol: rolling