# =============================================================================
# CoTrain Monorepo Workspace Configuration
# =============================================================================
# This file defines the workspace structure for the CoTrain project
# using pnpm workspaces for efficient dependency management

# Workspace packages configuration
packages:
  # Applications
  - 'apps/*'
  - 'apps/frontend'
  - 'apps/backend'
  - 'apps/admin'
  - 'apps/mobile'
  - 'apps/docs'
  - 'apps/storybook'
  
  # Core Services
  - 'CotrainCore'
  
  # Shared packages and libraries
  - 'packages/*'
  - 'packages/ui'
  - 'packages/shared'
  - 'packages/types'
  - 'packages/utils'
  - 'packages/config'
  - 'packages/eslint-config'
  - 'packages/tsconfig'
  - 'packages/tailwind-config'
  - 'packages/api-client'
  - 'packages/blockchain'
  - 'packages/database'
  - 'packages/auth'
  - 'packages/notifications'
  - 'packages/analytics'
  - 'packages/testing'
  
  # Libraries
  - 'libs/*'
  - 'libs/core'
  - 'libs/ai'
  - 'libs/crypto'
  - 'libs/storage'
  - 'libs/monitoring'
  
  # Smart contracts and blockchain related
  - 'contracts/*'
  - 'contracts/move'
  - 'contracts/scripts'
  - 'contracts/tests'
  
  # Configuration packages
  - 'configs/*'
  - 'configs/docker'
  - 'configs/kubernetes'
  - 'configs/terraform'
  
  # Development tools and scripts
  - 'tools/*'
  - 'tools/build'
  - 'tools/deploy'
  - 'tools/scripts'
  - 'tools/generators'
  
  # Documentation
  - 'docs/*'
  - 'docs/api'
  - 'docs/guides'
  - 'docs/examples'

# Catalog configuration for shared dependencies
catalog:
  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  react-router-dom: ^6.8.0
  
  # Next.js
  next: ^14.0.0
  
  # TypeScript
  typescript: ^5.3.0
  '@types/node': ^20.10.0
  '@types/react': ^18.2.0
  '@types/react-dom': ^18.2.0
  
  # NestJS
  '@nestjs/core': ^10.0.0
  '@nestjs/common': ^10.0.0
  '@nestjs/platform-express': ^10.0.0
  '@nestjs/config': ^3.0.0
  '@nestjs/typeorm': ^10.0.0
  '@nestjs/jwt': ^10.0.0
  '@nestjs/passport': ^10.0.0
  '@nestjs/swagger': ^7.0.0
  
  # Database
  typeorm: ^0.3.17
  pg: ^8.11.0
  redis: ^4.6.0
  
  # Aptos SDK
  '@aptos-labs/ts-sdk': ^1.0.0
  '@aptos-labs/wallet-adapter-react': ^3.0.0
  '@aptos-labs/wallet-adapter-ant-design': ^2.0.0
  
  # UI Libraries
  '@radix-ui/react-dialog': ^1.0.5
  '@radix-ui/react-dropdown-menu': ^2.0.6
  '@radix-ui/react-slot': ^1.0.2
  '@radix-ui/react-toast': ^1.1.5
  '@radix-ui/react-tooltip': ^1.0.7
  
  # Styling
  tailwindcss: ^3.4.0
  '@tailwindcss/forms': ^0.5.7
  '@tailwindcss/typography': ^0.5.10
  clsx: ^2.0.0
  class-variance-authority: ^0.7.0
  tailwind-merge: ^2.0.0
  
  # State Management
  zustand: ^4.4.0
  '@tanstack/react-query': ^5.0.0
  
  # Forms and Validation
  'react-hook-form': ^7.48.0
  '@hookform/resolvers': ^3.3.0
  zod: ^3.22.0
  
  # Testing
  jest: ^29.7.0
  '@testing-library/react': ^14.1.0
  '@testing-library/jest-dom': ^6.1.0
  '@testing-library/user-event': ^14.5.0
  vitest: ^1.0.0
  
  # Linting and Formatting
  eslint: ^8.55.0
  prettier: ^3.1.0
  '@typescript-eslint/eslint-plugin': ^6.13.0
  '@typescript-eslint/parser': ^6.13.0
  
  # Build Tools
  turbo: ^1.11.0
  tsup: ^8.0.0
  rollup: ^4.0.0
  vite: ^5.0.0
  
  # Utilities
  lodash: ^4.17.21
  date-fns: ^2.30.0
  uuid: ^9.0.0
  bcryptjs: ^2.4.3
  jsonwebtoken: ^9.0.0
  
  # Development
  nodemon: ^3.0.0
  concurrently: ^8.2.0
  cross-env: ^7.0.3
  rimraf: ^5.0.0

# Package manager settings
packageManager: pnpm@8.15.0

# Auto install peers
auto-install-peers: true

# Strict peer dependencies
strict-peer-dependencies: false

# Engine strict
engine-strict: true

# Link workspace packages
link-workspace-packages: true

# Prefer workspace packages
prefer-workspace-packages: true

# Save workspace protocol
save-workspace-protocol: rolling